# Assignment 1

In [ ]:
#by Zoya Fatima (20BCE11102)

In [1]:
name = "Zoya"
age = 21

print(name)
print(age)

In [3]:
X="Datascience is used to extract meaningful insights."
X.split()

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']

In [4]:
def mul(x, y):
    return x*y

mul(2,9)

In [6]:
# Dictionary of states and capitals
states_capitals = {
    'MP': 'Bhopal',
    'Maharashtra': 'Mumbai',
    'UP': 'Lucknow',
    'Bihar': 'Patna',
    'Gujarat': 'Gandhinagar'
}

# Print the keys (states)
print("States:")
for state in states_capitals.keys():
    print(state)

# Print the values (capitals)
print("\nCapitals:")
for capital in states_capitals.values():
    print(capital)


States:
MP
Maharashtra
UP
Bihar
Gujarat

Capitals:
Bhopal
Mumbai
Lucknow
Patna
Gandhinagar


In [7]:
numbers = list(range(1, 1001))

# Print the first 10 numbers
print(numbers[:10])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [9]:
# Dimension of the identity matrix
dimension = 4

# Create the identity matrix
identity_matrix = [[1 if i == j else 0 for j in range(dimension)] for i in range(dimension)]

# Print the identity matrix
for row in identity_matrix:
    print(row)


[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 1, 0]
[0, 0, 0, 1]


In [10]:
# Create the 3x3 matrix
matrix = [[j + 1 + i*3 for j in range(3)] for i in range(3)]

# Print the matrix
for row in matrix:
    print(row)


[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [11]:
import numpy as np

# Create two arrays
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Perform sum operation
result = array1 + array2

# Print the result
print(result)


[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [12]:
import pandas as pd

# Define the start and end dates
start_date = '2023-02-01'
end_date = '2023-03-01'

# Generate the series of dates
dates = pd.date_range(start=start_date, end=end_date, closed='left')

# Print the series of dates
for date in dates:
    print(date.strftime('%d-%m-%Y'))


01-02-2023
02-02-2023
03-02-2023
04-02-2023
05-02-2023
06-02-2023
07-02-2023
08-02-2023
09-02-2023
10-02-2023
11-02-2023
12-02-2023
13-02-2023
14-02-2023
15-02-2023
16-02-2023
17-02-2023
18-02-2023
19-02-2023
20-02-2023
21-02-2023
22-02-2023
23-02-2023
24-02-2023
25-02-2023
26-02-2023
27-02-2023
28-02-2023


C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11808\3583035386.py:8: FutureWarning: Argument `closed` is deprecated in favor of `inclusive`.
  dates = pd.date_range(start=start_date, end=end_date, closed='left')


In [13]:
import pandas as pd

# Given dictionary
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}

# Convert dictionary to dataframe
df = pd.DataFrame(dictionary)

# Display the dataframe
print(df)


     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
